//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.454.
// 
#pragma warning disable 1591

namespace eBriefing.com.metrostarsystems.ebriefingweb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Core_2Soap", Namespace="eBriefing")]
	public partial class Core_2 : System.Web.Services.Protocols.SoapHttpClientBridge {
        
        private System.Threading.SendOrPostCallback GetBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChaptersInBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPagesInBookOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Core_2(String url) {
            this.Url = url;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBooksCompletedEventHandler GetBooksCompleted;
        
        /// <remarks/>
        public event GetChaptersInBookCompletedEventHandler GetChaptersInBookCompleted;
        
        /// <remarks/>
        public event GetPagesInBookCompletedEventHandler GetPagesInBookCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/GetBooks", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetBooksReturn[] GetBooks() {
            object[] results = this.Invoke("GetBooks", new object[0]);
            return ((GetBooksReturn[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBooksAsync() {
            this.GetBooksAsync(null);
        }
        
        /// <remarks/>
        public void GetBooksAsync(object userState) {
            if ((this.GetBooksOperationCompleted == null)) {
                this.GetBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBooksOperationCompleted);
            }
            this.InvokeAsync("GetBooks", new object[0], this.GetBooksOperationCompleted, userState);
        }
        
        private void OnGetBooksOperationCompleted(object arg) {
            if ((this.GetBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBooksCompleted(this, new GetBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/GetChaptersInBook", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetChaptersInBookReturn[] GetChaptersInBook(string bookID) {
            object[] results = this.Invoke("GetChaptersInBook", new object[] {
                        bookID});
            return ((GetChaptersInBookReturn[])(results[0]));
        }
        
        /// <remarks/>
        public void GetChaptersInBookAsync(string bookID) {
            this.GetChaptersInBookAsync(bookID, null);
        }
        
        /// <remarks/>
        public void GetChaptersInBookAsync(string bookID, object userState) {
            if ((this.GetChaptersInBookOperationCompleted == null)) {
                this.GetChaptersInBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChaptersInBookOperationCompleted);
            }
            this.InvokeAsync("GetChaptersInBook", new object[] {
                        bookID}, this.GetChaptersInBookOperationCompleted, userState);
        }
        
        private void OnGetChaptersInBookOperationCompleted(object arg) {
            if ((this.GetChaptersInBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChaptersInBookCompleted(this, new GetChaptersInBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/GetPagesInBook", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetPagesInBookReturn[] GetPagesInBook(string bookID) {
            object[] results = this.Invoke("GetPagesInBook", new object[] {
                        bookID});
            return ((GetPagesInBookReturn[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPagesInBookAsync(string bookID) {
            this.GetPagesInBookAsync(bookID, null);
        }
        
        /// <remarks/>
        public void GetPagesInBookAsync(string bookID, object userState) {
            if ((this.GetPagesInBookOperationCompleted == null)) {
                this.GetPagesInBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPagesInBookOperationCompleted);
            }
            this.InvokeAsync("GetPagesInBook", new object[] {
                        bookID}, this.GetPagesInBookOperationCompleted, userState);
        }
        
        private void OnGetPagesInBookOperationCompleted(object arg) {
            if ((this.GetPagesInBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPagesInBookCompleted(this, new GetPagesInBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="eBriefing")]
    public partial class GetBooksReturn {
        
        private string idField;
        
        private string titleField;
        
        private string descriptionField;
        
        private int chapterCountField;
        
        private int pageCountField;
        
        private string smallImageURLField;
        
        private string largeImageURLField;
        
        private int imageVersionField;
        
        private int versionField;
        
        private System.DateTime dateAddedField;
        
        private System.DateTime dateModifiedField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int ChapterCount {
            get {
                return this.chapterCountField;
            }
            set {
                this.chapterCountField = value;
            }
        }
        
        /// <remarks/>
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        public string SmallImageURL {
            get {
                return this.smallImageURLField;
            }
            set {
                this.smallImageURLField = value;
            }
        }
        
        /// <remarks/>
        public string LargeImageURL {
            get {
                return this.largeImageURLField;
            }
            set {
                this.largeImageURLField = value;
            }
        }
        
        /// <remarks/>
        public int ImageVersion {
            get {
                return this.imageVersionField;
            }
            set {
                this.imageVersionField = value;
            }
        }
        
        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateAdded {
            get {
                return this.dateAddedField;
            }
            set {
                this.dateAddedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="eBriefing")]
    public partial class GetPagesInBookReturn {
        
        private string idField;
        
        private string uRLField;
        
        private int pageNumberField;
        
        private string mD5Field;
        
        private string typeField;
        
        private int versionField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MD5 {
            get {
                return this.mD5Field;
            }
            set {
                this.mD5Field = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="eBriefing")]
    public partial class GetChaptersInBookReturn {
        
        private string idField;
        
        private string titleField;
        
        private string descriptionField;
        
        private int pageCountField;
        
        private string smallImageURLField;
        
        private string largeImageURLField;
        
        private int imageVersionField;
        
        private string firstPageIDField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        public string SmallImageURL {
            get {
                return this.smallImageURLField;
            }
            set {
                this.smallImageURLField = value;
            }
        }
        
        /// <remarks/>
        public string LargeImageURL {
            get {
                return this.largeImageURLField;
            }
            set {
                this.largeImageURLField = value;
            }
        }
        
        /// <remarks/>
        public int ImageVersion {
            get {
                return this.imageVersionField;
            }
            set {
                this.imageVersionField = value;
            }
        }
        
        /// <remarks/>
        public string FirstPageID {
            get {
                return this.firstPageIDField;
            }
            set {
                this.firstPageIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBooksCompletedEventHandler(object sender, GetBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetBooksReturn[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetBooksReturn[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetChaptersInBookCompletedEventHandler(object sender, GetChaptersInBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChaptersInBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChaptersInBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetChaptersInBookReturn[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetChaptersInBookReturn[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPagesInBookCompletedEventHandler(object sender, GetPagesInBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPagesInBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPagesInBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetPagesInBookReturn[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPagesInBookReturn[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591