//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.454.
// 
#pragma warning disable 1591

namespace eBriefing.com.metrostarsystems.ebriefingweb2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SaveMyStuff_2Soap", Namespace="eBriefing")]
	public partial class SaveMyStuff_2 : System.Web.Services.Protocols.SoapHttpClientBridge {
        
        private System.Threading.SendOrPostCallback DeleteMyBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMyBookmarksOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMyTextAnnotationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMyPenAnnotationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMyStuffOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMyBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyBookmarksOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMyBookmarksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyTextAnnotationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMyTextAnnotationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveMyTextAnnotationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyPenAnnotationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMyPenAnnotationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveMyPenAnnotationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SaveMyStuff_2(String url) {
            this.Url = url;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteMyBooksCompletedEventHandler DeleteMyBooksCompleted;
        
        /// <remarks/>
        public event DeleteMyBookmarksCompletedEventHandler DeleteMyBookmarksCompleted;
        
        /// <remarks/>
        public event DeleteMyTextAnnotationsCompletedEventHandler DeleteMyTextAnnotationsCompleted;
        
        /// <remarks/>
        public event DeleteMyPenAnnotationsCompletedEventHandler DeleteMyPenAnnotationsCompleted;
        
        /// <remarks/>
        public event DeleteMyStuffCompletedEventHandler DeleteMyStuffCompleted;
        
        /// <remarks/>
        public event GetMyBooksCompletedEventHandler GetMyBooksCompleted;
        
        /// <remarks/>
        public event SetMyBooksCompletedEventHandler SetMyBooksCompleted;
        
        /// <remarks/>
        public event GetMyBookmarksCompletedEventHandler GetMyBookmarksCompleted;
        
        /// <remarks/>
        public event SetMyBookmarksCompletedEventHandler SetMyBookmarksCompleted;
        
        /// <remarks/>
        public event GetMyTextAnnotationsCompletedEventHandler GetMyTextAnnotationsCompleted;
        
        /// <remarks/>
        public event SetMyTextAnnotationCompletedEventHandler SetMyTextAnnotationCompleted;
        
        /// <remarks/>
        public event RemoveMyTextAnnotationCompletedEventHandler RemoveMyTextAnnotationCompleted;
        
        /// <remarks/>
        public event GetMyPenAnnotationsCompletedEventHandler GetMyPenAnnotationsCompleted;
        
        /// <remarks/>
        public event SetMyPenAnnotationCompletedEventHandler SetMyPenAnnotationCompleted;
        
        /// <remarks/>
        public event RemoveMyPenAnnotationCompletedEventHandler RemoveMyPenAnnotationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/DeleteMyBooks", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteMyBooks() {
            this.Invoke("DeleteMyBooks", new object[0]);
        }
        
        /// <remarks/>
        public void DeleteMyBooksAsync() {
            this.DeleteMyBooksAsync(null);
        }
        
        /// <remarks/>
        public void DeleteMyBooksAsync(object userState) {
            if ((this.DeleteMyBooksOperationCompleted == null)) {
                this.DeleteMyBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMyBooksOperationCompleted);
            }
            this.InvokeAsync("DeleteMyBooks", new object[0], this.DeleteMyBooksOperationCompleted, userState);
        }
        
        private void OnDeleteMyBooksOperationCompleted(object arg) {
            if ((this.DeleteMyBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMyBooksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/DeleteMyBookmarks", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteMyBookmarks() {
            this.Invoke("DeleteMyBookmarks", new object[0]);
        }
        
        /// <remarks/>
        public void DeleteMyBookmarksAsync() {
            this.DeleteMyBookmarksAsync(null);
        }
        
        /// <remarks/>
        public void DeleteMyBookmarksAsync(object userState) {
            if ((this.DeleteMyBookmarksOperationCompleted == null)) {
                this.DeleteMyBookmarksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMyBookmarksOperationCompleted);
            }
            this.InvokeAsync("DeleteMyBookmarks", new object[0], this.DeleteMyBookmarksOperationCompleted, userState);
        }
        
        private void OnDeleteMyBookmarksOperationCompleted(object arg) {
            if ((this.DeleteMyBookmarksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMyBookmarksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/DeleteMyTextAnnotations", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteMyTextAnnotations() {
            this.Invoke("DeleteMyTextAnnotations", new object[0]);
        }
        
        /// <remarks/>
        public void DeleteMyTextAnnotationsAsync() {
            this.DeleteMyTextAnnotationsAsync(null);
        }
        
        /// <remarks/>
        public void DeleteMyTextAnnotationsAsync(object userState) {
            if ((this.DeleteMyTextAnnotationsOperationCompleted == null)) {
                this.DeleteMyTextAnnotationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMyTextAnnotationsOperationCompleted);
            }
            this.InvokeAsync("DeleteMyTextAnnotations", new object[0], this.DeleteMyTextAnnotationsOperationCompleted, userState);
        }
        
        private void OnDeleteMyTextAnnotationsOperationCompleted(object arg) {
            if ((this.DeleteMyTextAnnotationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMyTextAnnotationsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/DeleteMyPenAnnotations", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteMyPenAnnotations() {
            this.Invoke("DeleteMyPenAnnotations", new object[0]);
        }
        
        /// <remarks/>
        public void DeleteMyPenAnnotationsAsync() {
            this.DeleteMyPenAnnotationsAsync(null);
        }
        
        /// <remarks/>
        public void DeleteMyPenAnnotationsAsync(object userState) {
            if ((this.DeleteMyPenAnnotationsOperationCompleted == null)) {
                this.DeleteMyPenAnnotationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMyPenAnnotationsOperationCompleted);
            }
            this.InvokeAsync("DeleteMyPenAnnotations", new object[0], this.DeleteMyPenAnnotationsOperationCompleted, userState);
        }
        
        private void OnDeleteMyPenAnnotationsOperationCompleted(object arg) {
            if ((this.DeleteMyPenAnnotationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMyPenAnnotationsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/DeleteMyStuff", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteMyStuff() {
            this.Invoke("DeleteMyStuff", new object[0]);
        }
        
        /// <remarks/>
        public void DeleteMyStuffAsync() {
            this.DeleteMyStuffAsync(null);
        }
        
        /// <remarks/>
        public void DeleteMyStuffAsync(object userState) {
            if ((this.DeleteMyStuffOperationCompleted == null)) {
                this.DeleteMyStuffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMyStuffOperationCompleted);
            }
            this.InvokeAsync("DeleteMyStuff", new object[0], this.DeleteMyStuffOperationCompleted, userState);
        }
        
        private void OnDeleteMyStuffOperationCompleted(object arg) {
            if ((this.DeleteMyStuffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMyStuffCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/GetMyBooks", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MyBookObj[] GetMyBooks() {
            object[] results = this.Invoke("GetMyBooks", new object[0]);
            return ((MyBookObj[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyBooksAsync() {
            this.GetMyBooksAsync(null);
        }
        
        /// <remarks/>
        public void GetMyBooksAsync(object userState) {
            if ((this.GetMyBooksOperationCompleted == null)) {
                this.GetMyBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyBooksOperationCompleted);
            }
            this.InvokeAsync("GetMyBooks", new object[0], this.GetMyBooksOperationCompleted, userState);
        }
        
        private void OnGetMyBooksOperationCompleted(object arg) {
            if ((this.GetMyBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyBooksCompleted(this, new GetMyBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/SetMyBooks", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetMyBooks(MyBookObj[] books) {
            this.Invoke("SetMyBooks", new object[] {
                        books});
        }
        
        /// <remarks/>
        public void SetMyBooksAsync(MyBookObj[] books) {
            this.SetMyBooksAsync(books, null);
        }
        
        /// <remarks/>
        public void SetMyBooksAsync(MyBookObj[] books, object userState) {
            if ((this.SetMyBooksOperationCompleted == null)) {
                this.SetMyBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMyBooksOperationCompleted);
            }
            this.InvokeAsync("SetMyBooks", new object[] {
                        books}, this.SetMyBooksOperationCompleted, userState);
        }
        
        private void OnSetMyBooksOperationCompleted(object arg) {
            if ((this.SetMyBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMyBooksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/GetMyBookmarks", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BookmarkObj[] GetMyBookmarks(string bookId) {
            object[] results = this.Invoke("GetMyBookmarks", new object[] {
                        bookId});
            return ((BookmarkObj[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyBookmarksAsync(string bookId) {
            this.GetMyBookmarksAsync(bookId, null);
        }
        
        /// <remarks/>
        public void GetMyBookmarksAsync(string bookId, object userState) {
            if ((this.GetMyBookmarksOperationCompleted == null)) {
                this.GetMyBookmarksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyBookmarksOperationCompleted);
            }
            this.InvokeAsync("GetMyBookmarks", new object[] {
                        bookId}, this.GetMyBookmarksOperationCompleted, userState);
        }
        
        private void OnGetMyBookmarksOperationCompleted(object arg) {
            if ((this.GetMyBookmarksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyBookmarksCompleted(this, new GetMyBookmarksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/SetMyBookmarks", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetMyBookmarks(BookmarkObj[] bookmarks) {
            this.Invoke("SetMyBookmarks", new object[] {
                        bookmarks});
        }
        
        /// <remarks/>
        public void SetMyBookmarksAsync(BookmarkObj[] bookmarks) {
            this.SetMyBookmarksAsync(bookmarks, null);
        }
        
        /// <remarks/>
        public void SetMyBookmarksAsync(BookmarkObj[] bookmarks, object userState) {
            if ((this.SetMyBookmarksOperationCompleted == null)) {
                this.SetMyBookmarksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMyBookmarksOperationCompleted);
            }
            this.InvokeAsync("SetMyBookmarks", new object[] {
                        bookmarks}, this.SetMyBookmarksOperationCompleted, userState);
        }
        
        private void OnSetMyBookmarksOperationCompleted(object arg) {
            if ((this.SetMyBookmarksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMyBookmarksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/GetMyTextAnnotations", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TextAnnotationObj[] GetMyTextAnnotations(string bookId) {
            object[] results = this.Invoke("GetMyTextAnnotations", new object[] {
                        bookId});
            return ((TextAnnotationObj[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyTextAnnotationsAsync(string bookId) {
            this.GetMyTextAnnotationsAsync(bookId, null);
        }
        
        /// <remarks/>
        public void GetMyTextAnnotationsAsync(string bookId, object userState) {
            if ((this.GetMyTextAnnotationsOperationCompleted == null)) {
                this.GetMyTextAnnotationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyTextAnnotationsOperationCompleted);
            }
            this.InvokeAsync("GetMyTextAnnotations", new object[] {
                        bookId}, this.GetMyTextAnnotationsOperationCompleted, userState);
        }
        
        private void OnGetMyTextAnnotationsOperationCompleted(object arg) {
            if ((this.GetMyTextAnnotationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyTextAnnotationsCompleted(this, new GetMyTextAnnotationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/SetMyTextAnnotation", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetMyTextAnnotation(string bookId, int bookVersion, string pageId, System.DateTime modifiedUtc, string content) {
            this.Invoke("SetMyTextAnnotation", new object[] {
                        bookId,
                        bookVersion,
                        pageId,
                        modifiedUtc,
                        content});
        }
        
        /// <remarks/>
        public void SetMyTextAnnotationAsync(string bookId, int bookVersion, string pageId, System.DateTime modifiedUtc, string content) {
            this.SetMyTextAnnotationAsync(bookId, bookVersion, pageId, modifiedUtc, content, null);
        }
        
        /// <remarks/>
        public void SetMyTextAnnotationAsync(string bookId, int bookVersion, string pageId, System.DateTime modifiedUtc, string content, object userState) {
            if ((this.SetMyTextAnnotationOperationCompleted == null)) {
                this.SetMyTextAnnotationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMyTextAnnotationOperationCompleted);
            }
            this.InvokeAsync("SetMyTextAnnotation", new object[] {
                        bookId,
                        bookVersion,
                        pageId,
                        modifiedUtc,
                        content}, this.SetMyTextAnnotationOperationCompleted, userState);
        }
        
        private void OnSetMyTextAnnotationOperationCompleted(object arg) {
            if ((this.SetMyTextAnnotationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMyTextAnnotationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/RemoveMyTextAnnotation", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveMyTextAnnotation(string bookId, string pageId, System.DateTime modifiedUtc) {
            this.Invoke("RemoveMyTextAnnotation", new object[] {
                        bookId,
                        pageId,
                        modifiedUtc});
        }
        
        /// <remarks/>
        public void RemoveMyTextAnnotationAsync(string bookId, string pageId, System.DateTime modifiedUtc) {
            this.RemoveMyTextAnnotationAsync(bookId, pageId, modifiedUtc, null);
        }
        
        /// <remarks/>
        public void RemoveMyTextAnnotationAsync(string bookId, string pageId, System.DateTime modifiedUtc, object userState) {
            if ((this.RemoveMyTextAnnotationOperationCompleted == null)) {
                this.RemoveMyTextAnnotationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveMyTextAnnotationOperationCompleted);
            }
            this.InvokeAsync("RemoveMyTextAnnotation", new object[] {
                        bookId,
                        pageId,
                        modifiedUtc}, this.RemoveMyTextAnnotationOperationCompleted, userState);
        }
        
        private void OnRemoveMyTextAnnotationOperationCompleted(object arg) {
            if ((this.RemoveMyTextAnnotationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveMyTextAnnotationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/GetMyPenAnnotations", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PenAnnotationObj[] GetMyPenAnnotations(string bookId, string platform) {
            object[] results = this.Invoke("GetMyPenAnnotations", new object[] {
                        bookId,
                        platform});
            return ((PenAnnotationObj[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyPenAnnotationsAsync(string bookId, string platform) {
            this.GetMyPenAnnotationsAsync(bookId, platform, null);
        }
        
        /// <remarks/>
        public void GetMyPenAnnotationsAsync(string bookId, string platform, object userState) {
            if ((this.GetMyPenAnnotationsOperationCompleted == null)) {
                this.GetMyPenAnnotationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyPenAnnotationsOperationCompleted);
            }
            this.InvokeAsync("GetMyPenAnnotations", new object[] {
                        bookId,
                        platform}, this.GetMyPenAnnotationsOperationCompleted, userState);
        }
        
        private void OnGetMyPenAnnotationsOperationCompleted(object arg) {
            if ((this.GetMyPenAnnotationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyPenAnnotationsCompleted(this, new GetMyPenAnnotationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/SetMyPenAnnotation", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetMyPenAnnotation(string bookId, int bookVersion, string pageId, string platform, System.DateTime modifiedUtc, string textData, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] imageData) {
            this.Invoke("SetMyPenAnnotation", new object[] {
                        bookId,
                        bookVersion,
                        pageId,
                        platform,
                        modifiedUtc,
                        textData,
                        imageData});
        }
        
        /// <remarks/>
        public void SetMyPenAnnotationAsync(string bookId, int bookVersion, string pageId, string platform, System.DateTime modifiedUtc, string textData, byte[] imageData) {
            this.SetMyPenAnnotationAsync(bookId, bookVersion, pageId, platform, modifiedUtc, textData, imageData, null);
        }
        
        /// <remarks/>
        public void SetMyPenAnnotationAsync(string bookId, int bookVersion, string pageId, string platform, System.DateTime modifiedUtc, string textData, byte[] imageData, object userState) {
            if ((this.SetMyPenAnnotationOperationCompleted == null)) {
                this.SetMyPenAnnotationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMyPenAnnotationOperationCompleted);
            }
            this.InvokeAsync("SetMyPenAnnotation", new object[] {
                        bookId,
                        bookVersion,
                        pageId,
                        platform,
                        modifiedUtc,
                        textData,
                        imageData}, this.SetMyPenAnnotationOperationCompleted, userState);
        }
        
        private void OnSetMyPenAnnotationOperationCompleted(object arg) {
            if ((this.SetMyPenAnnotationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMyPenAnnotationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("eBriefing/RemoveMyPenAnnotation", RequestNamespace="eBriefing", ResponseNamespace="eBriefing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveMyPenAnnotation(string bookId, string pageId, string platform, System.DateTime modifiedUtc) {
            this.Invoke("RemoveMyPenAnnotation", new object[] {
                        bookId,
                        pageId,
                        platform,
                        modifiedUtc});
        }
        
        /// <remarks/>
        public void RemoveMyPenAnnotationAsync(string bookId, string pageId, string platform, System.DateTime modifiedUtc) {
            this.RemoveMyPenAnnotationAsync(bookId, pageId, platform, modifiedUtc, null);
        }
        
        /// <remarks/>
        public void RemoveMyPenAnnotationAsync(string bookId, string pageId, string platform, System.DateTime modifiedUtc, object userState) {
            if ((this.RemoveMyPenAnnotationOperationCompleted == null)) {
                this.RemoveMyPenAnnotationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveMyPenAnnotationOperationCompleted);
            }
            this.InvokeAsync("RemoveMyPenAnnotation", new object[] {
                        bookId,
                        pageId,
                        platform,
                        modifiedUtc}, this.RemoveMyPenAnnotationOperationCompleted, userState);
        }
        
        private void OnRemoveMyPenAnnotationOperationCompleted(object arg) {
            if ((this.RemoveMyPenAnnotationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveMyPenAnnotationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="eBriefing")]
    public partial class MyBookObj {
        
        private string bookIdField;
        
        private int bookVersionField;
        
        private bool isFavoriteField;
        
        private System.DateTime modifiedUtcField;
        
        private bool removedField;
        
        /// <remarks/>
        public string BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
            }
        }
        
        /// <remarks/>
        public int BookVersion {
            get {
                return this.bookVersionField;
            }
            set {
                this.bookVersionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFavorite {
            get {
                return this.isFavoriteField;
            }
            set {
                this.isFavoriteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedUtc {
            get {
                return this.modifiedUtcField;
            }
            set {
                this.modifiedUtcField = value;
            }
        }
        
        /// <remarks/>
        public bool Removed {
            get {
                return this.removedField;
            }
            set {
                this.removedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="eBriefing")]
    public partial class PenAnnotationObj {
        
        private string bookIdField;
        
        private int bookVersionField;
        
        private string pageIdField;
        
        private string platformField;
        
        private string imageDataUrlField;
        
        private string textDataUrlField;
        
        private System.DateTime modifiedUtcField;
        
        private bool removedField;
        
        /// <remarks/>
        public string BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
            }
        }
        
        /// <remarks/>
        public int BookVersion {
            get {
                return this.bookVersionField;
            }
            set {
                this.bookVersionField = value;
            }
        }
        
        /// <remarks/>
        public string PageId {
            get {
                return this.pageIdField;
            }
            set {
                this.pageIdField = value;
            }
        }
        
        /// <remarks/>
        public string Platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string ImageDataUrl {
            get {
                return this.imageDataUrlField;
            }
            set {
                this.imageDataUrlField = value;
            }
        }
        
        /// <remarks/>
        public string TextDataUrl {
            get {
                return this.textDataUrlField;
            }
            set {
                this.textDataUrlField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedUtc {
            get {
                return this.modifiedUtcField;
            }
            set {
                this.modifiedUtcField = value;
            }
        }
        
        /// <remarks/>
        public bool Removed {
            get {
                return this.removedField;
            }
            set {
                this.removedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="eBriefing")]
    public partial class TextAnnotationObj {
        
        private string bookIdField;
        
        private int bookVersionField;
        
        private string pageIdField;
        
        private string valueUrlField;
        
        private System.DateTime modifiedUtcField;
        
        private bool removedField;
        
        /// <remarks/>
        public string BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
            }
        }
        
        /// <remarks/>
        public int BookVersion {
            get {
                return this.bookVersionField;
            }
            set {
                this.bookVersionField = value;
            }
        }
        
        /// <remarks/>
        public string PageId {
            get {
                return this.pageIdField;
            }
            set {
                this.pageIdField = value;
            }
        }
        
        /// <remarks/>
        public string ValueUrl {
            get {
                return this.valueUrlField;
            }
            set {
                this.valueUrlField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedUtc {
            get {
                return this.modifiedUtcField;
            }
            set {
                this.modifiedUtcField = value;
            }
        }
        
        /// <remarks/>
        public bool Removed {
            get {
                return this.removedField;
            }
            set {
                this.removedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="eBriefing")]
    public partial class BookmarkObj {
        
        private string bookIdField;
        
        private int bookVersionField;
        
        private string pageIdField;
        
        private string valueField;
        
        private System.DateTime modifiedUtcField;
        
        private bool removedField;
        
        /// <remarks/>
        public string BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
            }
        }
        
        /// <remarks/>
        public int BookVersion {
            get {
                return this.bookVersionField;
            }
            set {
                this.bookVersionField = value;
            }
        }
        
        /// <remarks/>
        public string PageId {
            get {
                return this.pageIdField;
            }
            set {
                this.pageIdField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedUtc {
            get {
                return this.modifiedUtcField;
            }
            set {
                this.modifiedUtcField = value;
            }
        }
        
        /// <remarks/>
        public bool Removed {
            get {
                return this.removedField;
            }
            set {
                this.removedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteMyBooksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteMyBookmarksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteMyTextAnnotationsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteMyPenAnnotationsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteMyStuffCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMyBooksCompletedEventHandler(object sender, GetMyBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MyBookObj[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MyBookObj[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetMyBooksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMyBookmarksCompletedEventHandler(object sender, GetMyBookmarksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyBookmarksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyBookmarksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookmarkObj[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookmarkObj[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetMyBookmarksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMyTextAnnotationsCompletedEventHandler(object sender, GetMyTextAnnotationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyTextAnnotationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyTextAnnotationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TextAnnotationObj[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TextAnnotationObj[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetMyTextAnnotationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RemoveMyTextAnnotationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMyPenAnnotationsCompletedEventHandler(object sender, GetMyPenAnnotationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyPenAnnotationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyPenAnnotationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PenAnnotationObj[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PenAnnotationObj[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetMyPenAnnotationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RemoveMyPenAnnotationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591